Atestados.UI/Controllers/FuncionarioController.cs
using Atestados.Datos.Modelo;
using Atestados.Negocios.Negocios;
using Atestados.Objetos.Dtos;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Atestados.UI.Controllers
{
    public class FuncionarioController : Controller
    {
        private readonly InformacionAtestado infoAtestado = new InformacionAtestado();
        private readonly InformacionGeneral infoGeneral = new InformacionGeneral();

        // GET: Funcionario
        public ActionResult Index()
        {
            if (Session["Usuario"] != null)
            {
                return View(ObtenerPersona());
            }
            else
            {
                return RedirectToAction("Index", "Login");
            }

        }

        [HttpPost]
        public ActionResult Index(PersonaDTO persona)
        {
            foreach(AtestadoDTO a in persona.PorEnviar)
            {
                if (a.MarcarEnviado)
                {
                    Atestado atestado = infoAtestado.CargarAtestadoParaEditar(a.AtestadoID);
                    atestado.Enviado = a.MarcarEnviado ? 1 : 0;
                    infoAtestado.EditarAtestado(atestado);
                }      
            }
            return View(ObtenerPersona());
        }

        private PersonaDTO ObtenerPersona()
        {
            PersonaDTO persona = infoGeneral.CargarPersona((int)Session["UsuarioID"]);
            persona.PorEnviar = infoAtestado.CargarAtestadosDePersonaEnviados((int)Session["UsuarioID"], 0);
            ViewBag.Enviados = infoAtestado.CargarAtestadosDePersonaEnviados((int)Session["UsuarioID"], 1);
            ViewBag.Rubros = new Dictionary<int, string>()
                {
                    { infoAtestado.ObtenerIDdeRubro("Artículo"), "Articulo"},
                    { infoAtestado.ObtenerIDdeRubro(""), "Atestados"},
                    { infoAtestado.ObtenerIDdeRubro("Capacitación profesional"), "Capacitacion"},
                    { infoAtestado.ObtenerIDdeRubro("Grados académicos"), "Certificado"},
                    { infoAtestado.ObtenerIDdeRubro("Idiomas"), "Idioma"},
                    { infoAtestado.ObtenerIDdeRubro("libro"), "Libro"},
                    { infoAtestado.ObtenerIDdeRubro("Obra administrativa de desarrollo"), "ObraAdministrativa"},
                    { infoAtestado.ObtenerIDdeRubro("Obra didáctica"), "ObraDidactica"},
                    { infoAtestado.ObtenerIDdeRubro("Ponencia"), "Ponencia"},
                    { infoAtestado.ObtenerIDdeRubro("Proyectos de investigación y extensión"), "Proyecto"},
                };
            return persona;
        }
    }
}

Atestados.UI/Views/Funcionario/Index.cshtml
@model  Atestados.Objetos.Dtos.PersonaDTO

@using Atestados.Objetos.Dtos;
@{ ViewBag.Title = "Principal";
    Layout = "~/Views/Shared/_LayoutFuncionario.cshtml";
}
@using Atestados.Negocios.Negocios;

<style>
    .table-wraper {
        display: block;
    }

    .scrollbar {
        position: relative;
        height: 230px;
        overflow: auto;
    }
</style>

<div class="container-fluid">
    <div class="row">
        <h2>Funcionario</h2>
        <hr />
    </div>
    <div class="row">
        <h4>Documentos sin enviar</h4>
    </div>
    <div class="row table-wraper scrollbar">
        @using (Html.BeginForm("Index", "Funcionario", FormMethod.Post))
        {
            @Html.HiddenFor(model => model.PersonaID)
            @Html.HiddenFor(model => model.Nombre)
            @Html.HiddenFor(model => model.PrimerApellido)
            @Html.HiddenFor(model => model.SegundoApellido)
            @Html.HiddenFor(model => model.Email)
            @Html.HiddenFor(model => model.Telefono)
            @Html.HiddenFor(model => model.TipoUsuario)
            @Html.HiddenFor(model => model.CategoriaActual)
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th scope="col" style="width:5%">
                            <input type="checkbox" id="seleccionarTodos" />
                        </th>
                        <th scope="col">
                            ID
                        </th>
                        <th scope="col">
                            Rubro
                        </th>
                        <th scope="col">
                            Nombre
                        </th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @for (int i = 0; i < Model.PorEnviar.Count; i++)
                    {
                    <tr>
                        <td scope="col">
                            @Html.CheckBoxFor(m => m.PorEnviar[i].MarcarEnviado)
                        </td>
                        <td scope="col">
                            @Html.TextBoxFor(m => m.PorEnviar[i].AtestadoID, new { @readonly = "readonly" })
                        </td>
                        <td scope="col">
                            @Html.DisplayFor(model => model.PorEnviar[i].Rubro.Nombre)
                        </td>
                        <td scope="col">
                            @Html.DisplayFor(model => model.PorEnviar[i].Nombre)
                        </td>
                        <td>
                            <a rubro="@Model.PorEnviar[i].RubroID" atestado="@Model.PorEnviar[i].AtestadoID" action="Editar">Editar</a> |
                            <a rubro="@Model.PorEnviar[i].RubroID" atestado="@Model.PorEnviar[i].AtestadoID" action="Ver">Ver</a> |
                            <a rubro="@Model.PorEnviar[i].RubroID" atestado="@Model.PorEnviar[i].AtestadoID" action="Borrar">Borrar</a>
                        </td>
                    </tr>
                    }
                </tbody>
            </table>
            <div class="row">
                <div class="form-group">
                    <div class="col-md-10">
                        <input type="submit" value="Enviar" class="btn btn-default" id="submit" />
                    </div>
                </div>
            </div>
        }
    </div>
    <div class="row">
        <h4>Documentos enviados</h4>
    </div>
    <div class="row table-wraper scrollbar">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th scope="col">
                        Rubro
                    </th>
                    <th scope="col">
                        Nombre
                    </th>
                    <th scope="col">

                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (AtestadoDTO item in ViewBag.Enviados)
                {
                    <tr>
                        <td scope="col">
                            @item.Rubro.Nombre
                        </td>
                        <td scope="col">
                            @item.Nombre
                        </td>
                        <td scope="col">
                            <a rubro="@item.RubroID" atestado="@item.AtestadoID" action="Ver">Ver</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
<script type="text/javascript">
    @{InformacionAtestado infoAtestado = new InformacionAtestado(); }

    var controllers = []
    controllers.push(@infoAtestado.ObtenerIDdeRubro("Artículo"))
    controllers.push(@infoAtestado.ObtenerIDdeRubro("Capacitación profesional"))
    controllers.push(@infoAtestado.ObtenerIDdeRubro("Grados académicos"))
    controllers.push(@infoAtestado.ObtenerIDdeRubro("Idiomas"))
    controllers.push(@infoAtestado.ObtenerIDdeRubro("libro"))
    controllers.push(@infoAtestado.ObtenerIDdeRubro("Obra administrativa de desarrollo"))
    controllers.push(@infoAtestado.ObtenerIDdeRubro("Obra didáctica"))
    controllers.push(@infoAtestado.ObtenerIDdeRubro("Ponencia"))
    controllers.push(@infoAtestado.ObtenerIDdeRubro("Proyectos de investigación y extensión"))

    $('#seleccionarTodos').click(function (e) {
            var table = $(e.target).closest('table');
        $('td input:checkbox', table).prop('checked', this.checked);
    });

    var url = "";

    $("a").click(e => {
        var rubro = $(e.target).attr('rubro')
        var atestado = $(e.target).attr('atestado')
        var action = $(e.target).attr('action')
        switch (rubro) {
            case controllers[0].toString():
                url = "/Articulo/" + action + "/" + atestado  // para que funcione en local se debe colocar /Atestados antes | se quita para el deploy
                break;
            case controllers[1].toString():
                url = "/Capacitacion/" + action + "/" + atestado
                break;
            case controllers[2].toString():
                url = "/Certificado/" + action + "/" + atestado
                break;
            case controllers[3].toString():
                url = "/Idioma/" + action + "/" + atestado
                break;
            case controllers[4].toString():
                url = "/Libro/" + action + "/" + atestado
                break;
            case controllers[5].toString():
                url = "/ObraAdministrativa/" + action + "/" + atestado
                break;
            case controllers[6].toString():
                url = "/ObraDidactica/" + action + "/" + atestado
                break;
            case controllers[7].toString():
                url = "/Ponencia/" + action + "/" + atestado
                break;
            case controllers[8].toString():
                url = "/Proyecto/" + action + "/" + atestado
                break;
            default:
                url = "/" + action + "/" + atestado
        }

        if(action == "Ver" || action == "Editar")
            window.location.href = url
        else
            console.log("borrar")
    });
</script>